import { afterEach } from "vitest";

const ownedKeys = [
  "TELEGRAM_WEBHOOK_SECRET",
  "OPERATOR_SECRET",
  "CRON_SECRET",
  "E2E_TEST_ROUTES",
  "TELEGRAM_BOT_TOKEN",
  "TELEGRAM_API_ROOT",
  "TELEGRAM_DELIVERY_MODE",
  "VERCEL_ENV",
  "ANTHROPIC_API_KEY",
  "OPENAI_API_KEY",
  "RATE_LIMIT_WINDOW_SECONDS",
  "RATE_LIMIT_WEBHOOK_MAX",
  "RATE_LIMIT_TRIGGER_MAX",
  "RATE_LIMIT_CRON_MAX",
  "QUEUE_DRAIN_LIMIT",
  "QUEUE_LEASE_SECONDS",
  "QUEUE_MAX_ATTEMPTS",
  "QUEUE_BACKOFF_BASE_SECONDS",
  "QUEUE_BACKOFF_MAX_SECONDS",
];

afterEach(() => {
  for (const key of ownedKeys) {
    delete process.env[key];
  }
});
